import styles from '../styles/index.module.css';

import Head from 'next/head'
import Profile from '../components/profile';
import Posts from '../components/posts';

export default function Home() {
  return (
    <div className={styles.App}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Profile />
        <Posts />
      </div>
    </div>
  )
}